default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: kid_friendly_videos_development
  username: kid_friendly_videos_development
  password: password

test:
  <<: *default
  database: kid_friendly_videos_test
  username: kid_friendly_videos_test
  password: password

production:
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: "kid_friendly_videos"
