default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: autism_video_recommender_development
  username: autism_video_recommender_development
  password: password

test:
  <<: *default
  database: autism_video_recommender_test
  username: autism_video_recommender_test
  password: password

production:
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: "autism_video_recommender"
